version: "3.9"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "9001:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
  node-app:
    build: .
    env_file:
      - web-variables.env
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - smartsoft:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=smartsoft
      - POSTGRES_USER=mabravo153
      - POSTGRES_PASSWORD=barranquilla1.
volumes:
  smartsoft:
