version: "3.9"
services:
  node-app:
    build: .
    env_file:
      - web-variables.env
    ports:
      - "9000:9000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - smartsoft:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=smartsoft
      - POSTGRES_USER=mabravo153
      - POSTGRES_PASSWORD=barranquilla1.
volumes:
  smartsoft:
